#%RAML 1.0
title: PassengerCheckin
version: 1.0
baseUri: http://localhost/pnr/{version}
/pnrcheckin:
  displayName: Checkin PNR
  post:
    description: checkin pnr
    body:
      application/xml:
        schema: !include PNRCheckinRequest.xsd
    responses:
      200:
        body:
          application/xml:
            schema: !include PNRCheckinResponse.xsd