#%RAML 1.0
title: Order Management
version: v1
baseUri: http://localhost:9321/order/{version}
securitySchemes: 
  oauth_2_0:
    type: OAuth 2.0
    description: |
    settings: 
      authorizationUri: https://dev-536852.oktapreview.com/oauth2/default/v1/authorize
      accessTokenUri: https://dev-536852.oktapreview.com/oauth2/default/v1/token
      authorizationGrants: [authorization_code,implicit,client_credentials,password]
/createorder:
  displayName: Create Order
  post:
    description: Create Order
    body:
      application/json:
        schema: !include ./order/CreateOrderRequest.json
    responses:
      200:
        body:
          application/json:
            schema: !include ./order/CreateOrderResponse.json
/getorders:
  displayName: Get Orders
  get: 
    description: Get Orders
    responses: 
      200:
        body: 
          application/json: 
            schema: !include ./order/GetOrdersResponse.json      